// Generated from public Korean administrative district coordinate references.
// Keep this file small and dependency-free so location fallback works offline.
// Coordinate seed: https://gist.github.com/pjt3591oo/efaa02ff73538dd2f51f6caae939f836
// English labels reference: https://github.com/southkorea/southkorea-maps

class ManualLocationOption {
  const ManualLocationOption({
    required this.id,
    required this.provinceId,
    required this.provinceKo,
    required this.provinceEn,
    required this.labelKo,
    required this.labelEn,
    required this.lat,
    required this.lng,
  });

  final String id;
  final String provinceId;
  final String provinceKo;
  final String provinceEn;
  final String labelKo;
  final String labelEn;
  final double lat;
  final double lng;

  String label(String language) =>
      _localized(language, ko: labelKo, en: labelEn);
  String provinceLabel(String language) =>
      _localized(language, ko: provinceKo, en: provinceEn);
  String fullLabel(String language) {
    final label = this.label(language);
    final province = provinceLabel(language);
    return label == province ? label : '$province $label';
  }

  bool matches(String query) {
    final normalized = query.trim().toLowerCase();
    if (normalized.isEmpty) return true;
    return labelKo.contains(normalized) ||
        provinceKo.contains(normalized) ||
        labelEn.toLowerCase().contains(normalized) ||
        provinceEn.toLowerCase().contains(normalized) ||
        '$provinceKo $labelKo'.contains(normalized) ||
        '$provinceEn $labelEn'.toLowerCase().contains(normalized);
  }
}

class ManualLocationProvince {
  const ManualLocationProvince({
    required this.id,
    required this.labelKo,
    required this.labelEn,
    required this.shortKo,
    required this.shortEn,
    required this.options,
  });

  final String id;
  final String labelKo;
  final String labelEn;
  final String shortKo;
  final String shortEn;
  final List<ManualLocationOption> options;

  String label(String language) =>
      _localized(language, ko: labelKo, en: labelEn);
  String shortLabel(String language) =>
      _localized(language, ko: shortKo, en: shortEn);
}

const List<String> featuredManualLocationIds = <String>[
  'seoul-jung',
  'gyeonggi-suwon',
  'busan-haeundae',
  'jeju-jeju',
  'sejong-sejong',
];

const List<ManualLocationProvince> manualLocationProvinces =
    <ManualLocationProvince>[
      ManualLocationProvince(
        id: 'seoul',
        labelKo: '서울특별시',
        labelEn: 'Seoul',
        shortKo: '서울',
        shortEn: 'Seoul',
        options: <ManualLocationOption>[
          ManualLocationOption(
            id: 'seoul-gangnam',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '강남구',
            labelEn: 'Gangnam-gu',
            lat: 37.49510,
            lng: 127.06278,
          ),
          ManualLocationOption(
            id: 'seoul-gangdong',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '강동구',
            labelEn: 'Gangdong-gu',
            lat: 37.55274,
            lng: 127.14546,
          ),
          ManualLocationOption(
            id: 'seoul-gangbuk',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '강북구',
            labelEn: 'Gangbuk-gu',
            lat: 37.63490,
            lng: 127.02015,
          ),
          ManualLocationOption(
            id: 'seoul-gangseo',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '강서구',
            labelEn: 'Gangseo-gu',
            lat: 37.56227,
            lng: 126.81622,
          ),
          ManualLocationOption(
            id: 'seoul-gwanak',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '관악구',
            labelEn: 'Gwanak-gu',
            lat: 37.47876,
            lng: 126.95235,
          ),
          ManualLocationOption(
            id: 'seoul-gwangjin',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '광진구',
            labelEn: 'Gwangjin-gu',
            lat: 37.53913,
            lng: 127.08366,
          ),
          ManualLocationOption(
            id: 'seoul-guro',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '구로구',
            labelEn: 'Guro-gu',
            lat: 37.49447,
            lng: 126.85020,
          ),
          ManualLocationOption(
            id: 'seoul-geumcheon',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '금천구',
            labelEn: 'Geumcheon-gu',
            lat: 37.47486,
            lng: 126.89106,
          ),
          ManualLocationOption(
            id: 'seoul-nowon',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '노원구',
            labelEn: 'Nowon-gu',
            lat: 37.66045,
            lng: 127.06718,
          ),
          ManualLocationOption(
            id: 'seoul-dobong',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '도봉구',
            labelEn: 'Dobong-gu',
            lat: 37.65066,
            lng: 127.03011,
          ),
          ManualLocationOption(
            id: 'seoul-dongdaemun',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '동대문구',
            labelEn: 'Dongdaemun-gu',
            lat: 37.58189,
            lng: 127.05408,
          ),
          ManualLocationOption(
            id: 'seoul-dongjak',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '동작구',
            labelEn: 'Dongjak-gu',
            lat: 37.50056,
            lng: 126.95149,
          ),
          ManualLocationOption(
            id: 'seoul-mapo',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '마포구',
            labelEn: 'Mapo-gu',
            lat: 37.55438,
            lng: 126.90926,
          ),
          ManualLocationOption(
            id: 'seoul-seodaemun',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '서대문구',
            labelEn: 'Seodaemun-gu',
            lat: 37.57809,
            lng: 126.93506,
          ),
          ManualLocationOption(
            id: 'seoul-seocho',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '서초구',
            labelEn: 'Seocho-gu',
            lat: 37.49447,
            lng: 127.01088,
          ),
          ManualLocationOption(
            id: 'seoul-seongdong',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '성동구',
            labelEn: 'Seongdong-gu',
            lat: 37.54784,
            lng: 127.02461,
          ),
          ManualLocationOption(
            id: 'seoul-seongbuk',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '성북구',
            labelEn: 'Seongbuk-gu',
            lat: 37.60267,
            lng: 127.01448,
          ),
          ManualLocationOption(
            id: 'seoul-songpa',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '송파구',
            labelEn: 'Songpa-gu',
            lat: 37.50210,
            lng: 127.11113,
          ),
          ManualLocationOption(
            id: 'seoul-yangcheon',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '양천구',
            labelEn: 'Yangcheon-gu',
            lat: 37.52056,
            lng: 126.87472,
          ),
          ManualLocationOption(
            id: 'seoul-yeongdeungpo',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '영등포구',
            labelEn: 'Yeongdeungpo-gu',
            lat: 37.52606,
            lng: 126.90308,
          ),
          ManualLocationOption(
            id: 'seoul-yongsan',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '용산구',
            labelEn: 'Yongsan-gu',
            lat: 37.53391,
            lng: 126.97750,
          ),
          ManualLocationOption(
            id: 'seoul-eunpyeong',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '은평구',
            labelEn: 'Eunpyeong-gu',
            lat: 37.61846,
            lng: 126.92780,
          ),
          ManualLocationOption(
            id: 'seoul-jongno',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '종로구',
            labelEn: 'Jongno-gu',
            lat: 37.57290,
            lng: 126.97928,
          ),
          ManualLocationOption(
            id: 'seoul-jung',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '중구',
            labelEn: 'Jung-gu',
            lat: 37.55986,
            lng: 126.99398,
          ),
          ManualLocationOption(
            id: 'seoul-jungnang',
            provinceId: 'seoul',
            provinceKo: '서울특별시',
            provinceEn: 'Seoul',
            labelKo: '중랑구',
            labelEn: 'Jungnang-gu',
            lat: 37.60199,
            lng: 127.10461,
          ),
        ],
      ),
      ManualLocationProvince(
        id: 'busan',
        labelKo: '부산광역시',
        labelEn: 'Busan',
        shortKo: '부산',
        shortEn: 'Busan',
        options: <ManualLocationOption>[
          ManualLocationOption(
            id: 'busan-gangseo',
            provinceId: 'busan',
            provinceKo: '부산광역시',
            provinceEn: 'Busan',
            labelKo: '강서구',
            labelEn: 'Gangseo-gu',
            lat: 35.15930,
            lng: 128.93300,
          ),
          ManualLocationOption(
            id: 'busan-geumjeong',
            provinceId: 'busan',
            provinceKo: '부산광역시',
            provinceEn: 'Busan',
            labelKo: '금정구',
            labelEn: 'Geumjeong-gu',
            lat: 35.25863,
            lng: 129.09010,
          ),
          ManualLocationOption(
            id: 'busan-gijang',
            provinceId: 'busan',
            provinceKo: '부산광역시',
            provinceEn: 'Busan',
            labelKo: '기장군',
            labelEn: 'Gijang-gun',
            lat: 35.29721,
            lng: 129.20076,
          ),
          ManualLocationOption(
            id: 'busan-nam',
            provinceId: 'busan',
            provinceKo: '부산광역시',
            provinceEn: 'Busan',
            labelKo: '남구',
            labelEn: 'Nam-gu',
            lat: 35.13648,
            lng: 129.08266,
          ),
          ManualLocationOption(
            id: 'busan-dong',
            provinceId: 'busan',
            provinceKo: '부산광역시',
            provinceEn: 'Busan',
            labelKo: '동구',
            labelEn: 'Dong-gu',
            lat: 35.12468,
            lng: 129.03432,
          ),
          ManualLocationOption(
            id: 'busan-dongnae',
            provinceId: 'busan',
            provinceKo: '부산광역시',
            provinceEn: 'Busan',
            labelKo: '동래구',
            labelEn: 'Dongnae-gu',
            lat: 35.20447,
            lng: 129.07800,
          ),
          ManualLocationOption(
            id: 'busan-busanjin',
            provinceId: 'busan',
            provinceKo: '부산광역시',
            provinceEn: 'Busan',
            labelKo: '부산진구',
            labelEn: 'Busanjin-gu',
            lat: 35.16293,
            lng: 129.05133,
          ),
          ManualLocationOption(
            id: 'busan-buk',
            provinceId: 'busan',
            provinceKo: '부산광역시',
            provinceEn: 'Busan',
            labelKo: '북구',
            labelEn: 'Buk-gu',
            lat: 35.19724,
            lng: 128.99134,
          ),
          ManualLocationOption(
            id: 'busan-sasang',
            provinceId: 'busan',
            provinceKo: '부산광역시',
            provinceEn: 'Busan',
            labelKo: '사상구',
            labelEn: 'Sasang-gu',
            lat: 35.14479,
            lng: 128.97986,
          ),
          ManualLocationOption(
            id: 'busan-saha',
            provinceId: 'busan',
            provinceKo: '부산광역시',
            provinceEn: 'Busan',
            labelKo: '사하구',
            labelEn: 'Saha-gu',
            lat: 35.08552,
            lng: 128.98725,
          ),
          ManualLocationOption(
            id: 'busan-seo',
            provinceId: 'busan',
            provinceKo: '부산광역시',
            provinceEn: 'Busan',
            labelKo: '서구',
            labelEn: 'Seo-gu',
            lat: 35.12529,
            lng: 129.01946,
          ),
          ManualLocationOption(
            id: 'busan-suyeong',
            provinceId: 'busan',
            provinceKo: '부산광역시',
            provinceEn: 'Busan',
            labelKo: '수영구',
            labelEn: 'Suyeong-gu',
            lat: 35.15627,
            lng: 129.11253,
          ),
          ManualLocationOption(
            id: 'busan-yeonje',
            provinceId: 'busan',
            provinceKo: '부산광역시',
            provinceEn: 'Busan',
            labelKo: '연제구',
            labelEn: 'Yeonje-gu',
            lat: 35.18206,
            lng: 129.08285,
          ),
          ManualLocationOption(
            id: 'busan-yeongdo',
            provinceId: 'busan',
            provinceKo: '부산광역시',
            provinceEn: 'Busan',
            labelKo: '영도구',
            labelEn: 'Yeongdo-gu',
            lat: 35.07849,
            lng: 129.06483,
          ),
          ManualLocationOption(
            id: 'busan-jung',
            provinceId: 'busan',
            provinceKo: '부산광역시',
            provinceEn: 'Busan',
            labelKo: '중구',
            labelEn: 'Jung-gu',
            lat: 35.10594,
            lng: 129.03331,
          ),
          ManualLocationOption(
            id: 'busan-haeundae',
            provinceId: 'busan',
            provinceKo: '부산광역시',
            provinceEn: 'Busan',
            labelKo: '해운대구',
            labelEn: 'Haeundae-gu',
            lat: 35.16665,
            lng: 129.16792,
          ),
        ],
      ),
      ManualLocationProvince(
        id: 'daegu',
        labelKo: '대구광역시',
        labelEn: 'Daegu',
        shortKo: '대구',
        shortEn: 'Daegu',
        options: <ManualLocationOption>[
          ManualLocationOption(
            id: 'daegu-gunwi',
            provinceId: 'daegu',
            provinceKo: '대구광역시',
            provinceEn: 'Daegu',
            labelKo: '군위군',
            labelEn: 'Gunwi-gun',
            lat: 36.16995,
            lng: 128.64705,
          ),
          ManualLocationOption(
            id: 'daegu-nam',
            provinceId: 'daegu',
            provinceKo: '대구광역시',
            provinceEn: 'Daegu',
            labelKo: '남구',
            labelEn: 'Nam-gu',
            lat: 35.84119,
            lng: 128.58800,
          ),
          ManualLocationOption(
            id: 'daegu-dalseo',
            provinceId: 'daegu',
            provinceKo: '대구광역시',
            provinceEn: 'Daegu',
            labelKo: '달서구',
            labelEn: 'Dalseo-gu',
            lat: 35.82569,
            lng: 128.52403,
          ),
          ManualLocationOption(
            id: 'daegu-dalseong',
            provinceId: 'daegu',
            provinceKo: '대구광역시',
            provinceEn: 'Daegu',
            labelKo: '달성군',
            labelEn: 'Dalseong-gun',
            lat: 35.77467,
            lng: 128.42955,
          ),
          ManualLocationOption(
            id: 'daegu-dong',
            provinceId: 'daegu',
            provinceKo: '대구광역시',
            provinceEn: 'Daegu',
            labelKo: '동구',
            labelEn: 'Dong-gu',
            lat: 35.88566,
            lng: 128.63296,
          ),
          ManualLocationOption(
            id: 'daegu-buk',
            provinceId: 'daegu',
            provinceKo: '대구광역시',
            provinceEn: 'Daegu',
            labelKo: '북구',
            labelEn: 'Buk-gu',
            lat: 35.90000,
            lng: 128.59175,
          ),
          ManualLocationOption(
            id: 'daegu-seo',
            provinceId: 'daegu',
            provinceKo: '대구광역시',
            provinceEn: 'Daegu',
            labelKo: '서구',
            labelEn: 'Seo-gu',
            lat: 35.87465,
            lng: 128.55109,
          ),
          ManualLocationOption(
            id: 'daegu-suseong',
            provinceId: 'daegu',
            provinceKo: '대구광역시',
            provinceEn: 'Daegu',
            labelKo: '수성구',
            labelEn: 'Suseong-gu',
            lat: 35.85905,
            lng: 128.62625,
          ),
          ManualLocationOption(
            id: 'daegu-jung',
            provinceId: 'daegu',
            provinceKo: '대구광역시',
            provinceEn: 'Daegu',
            labelKo: '중구',
            labelEn: 'Jung-gu',
            lat: 35.86678,
            lng: 128.59538,
          ),
        ],
      ),
      ManualLocationProvince(
        id: 'incheon',
        labelKo: '인천광역시',
        labelEn: 'Incheon',
        shortKo: '인천',
        shortEn: 'Incheon',
        options: <ManualLocationOption>[
          ManualLocationOption(
            id: 'incheon-ganghwa',
            provinceId: 'incheon',
            provinceKo: '인천광역시',
            provinceEn: 'Incheon',
            labelKo: '강화군',
            labelEn: 'Ganghwa-gun',
            lat: 37.74722,
            lng: 126.48556,
          ),
          ManualLocationOption(
            id: 'incheon-gyeyang',
            provinceId: 'incheon',
            provinceKo: '인천광역시',
            provinceEn: 'Incheon',
            labelKo: '계양구',
            labelEn: 'Gyeyang-gu',
            lat: 37.52306,
            lng: 126.74472,
          ),
          ManualLocationOption(
            id: 'incheon-namdong',
            provinceId: 'incheon',
            provinceKo: '인천광역시',
            provinceEn: 'Incheon',
            labelKo: '남동구',
            labelEn: 'Namdong-gu',
            lat: 37.41831,
            lng: 126.71840,
          ),
          ManualLocationOption(
            id: 'incheon-dong',
            provinceId: 'incheon',
            provinceKo: '인천광역시',
            provinceEn: 'Incheon',
            labelKo: '동구',
            labelEn: 'Dong-gu',
            lat: 37.48375,
            lng: 126.63690,
          ),
          ManualLocationOption(
            id: 'incheon-michuhol',
            provinceId: 'incheon',
            provinceKo: '인천광역시',
            provinceEn: 'Incheon',
            labelKo: '미추홀구',
            labelEn: 'Michuhol-gu',
            lat: 37.46362,
            lng: 126.65000,
          ),
          ManualLocationOption(
            id: 'incheon-bupyeong',
            provinceId: 'incheon',
            provinceKo: '인천광역시',
            provinceEn: 'Incheon',
            labelKo: '부평구',
            labelEn: 'Bupyeong-gu',
            lat: 37.49720,
            lng: 126.71107,
          ),
          ManualLocationOption(
            id: 'incheon-seo',
            provinceId: 'incheon',
            provinceKo: '인천광역시',
            provinceEn: 'Incheon',
            labelKo: '서구',
            labelEn: 'Seo-gu',
            lat: 37.55233,
            lng: 126.65543,
          ),
          ManualLocationOption(
            id: 'incheon-yeonsu',
            provinceId: 'incheon',
            provinceKo: '인천광역시',
            provinceEn: 'Incheon',
            labelKo: '연수구',
            labelEn: 'Yeonsu-gu',
            lat: 37.41911,
            lng: 126.66489,
          ),
          ManualLocationOption(
            id: 'incheon-ongjin',
            provinceId: 'incheon',
            provinceKo: '인천광역시',
            provinceEn: 'Incheon',
            labelKo: '옹진군',
            labelEn: 'Ongjin-gun',
            lat: 37.23361,
            lng: 126.12305,
          ),
          ManualLocationOption(
            id: 'incheon-jung',
            provinceId: 'incheon',
            provinceKo: '인천광역시',
            provinceEn: 'Incheon',
            labelKo: '중구',
            labelEn: 'Jung-gu',
            lat: 37.47353,
            lng: 126.62151,
          ),
        ],
      ),
      ManualLocationProvince(
        id: 'gwangju',
        labelKo: '광주광역시',
        labelEn: 'Gwangju',
        shortKo: '광주',
        shortEn: 'Gwangju',
        options: <ManualLocationOption>[
          ManualLocationOption(
            id: 'gwangju-gwangsan',
            provinceId: 'gwangju',
            provinceKo: '광주광역시',
            provinceEn: 'Gwangju',
            labelKo: '광산구',
            labelEn: 'Gwangsan-gu',
            lat: 35.16158,
            lng: 126.80810,
          ),
          ManualLocationOption(
            id: 'gwangju-nam',
            provinceId: 'gwangju',
            provinceKo: '광주광역시',
            provinceEn: 'Gwangju',
            labelKo: '남구',
            labelEn: 'Nam-gu',
            lat: 35.12159,
            lng: 126.90943,
          ),
          ManualLocationOption(
            id: 'gwangju-dong',
            provinceId: 'gwangju',
            provinceKo: '광주광역시',
            provinceEn: 'Gwangju',
            labelKo: '동구',
            labelEn: 'Dong-gu',
            lat: 35.14592,
            lng: 126.92320,
          ),
          ManualLocationOption(
            id: 'gwangju-buk',
            provinceId: 'gwangju',
            provinceKo: '광주광역시',
            provinceEn: 'Gwangju',
            labelKo: '북구',
            labelEn: 'Buk-gu',
            lat: 35.19232,
            lng: 126.92439,
          ),
          ManualLocationOption(
            id: 'gwangju-seo',
            provinceId: 'gwangju',
            provinceKo: '광주광역시',
            provinceEn: 'Gwangju',
            labelKo: '서구',
            labelEn: 'Seo-gu',
            lat: 35.15248,
            lng: 126.89106,
          ),
        ],
      ),
      ManualLocationProvince(
        id: 'daejeon',
        labelKo: '대전광역시',
        labelEn: 'Daejeon',
        shortKo: '대전',
        shortEn: 'Daejeon',
        options: <ManualLocationOption>[
          ManualLocationOption(
            id: 'daejeon-daedeok',
            provinceId: 'daejeon',
            provinceKo: '대전광역시',
            provinceEn: 'Daejeon',
            labelKo: '대덕구',
            labelEn: 'Daedeok-gu',
            lat: 36.39591,
            lng: 127.43437,
          ),
          ManualLocationOption(
            id: 'daejeon-dong',
            provinceId: 'daejeon',
            provinceKo: '대전광역시',
            provinceEn: 'Daejeon',
            labelKo: '동구',
            labelEn: 'Dong-gu',
            lat: 36.32938,
            lng: 127.44313,
          ),
          ManualLocationOption(
            id: 'daejeon-seo',
            provinceId: 'daejeon',
            provinceKo: '대전광역시',
            provinceEn: 'Daejeon',
            labelKo: '서구',
            labelEn: 'Seo-gu',
            lat: 36.28071,
            lng: 127.34533,
          ),
          ManualLocationOption(
            id: 'daejeon-yuseong',
            provinceId: 'daejeon',
            provinceKo: '대전광역시',
            provinceEn: 'Daejeon',
            labelKo: '유성구',
            labelEn: 'Yuseong-gu',
            lat: 36.36685,
            lng: 127.32700,
          ),
          ManualLocationOption(
            id: 'daejeon-jung',
            provinceId: 'daejeon',
            provinceKo: '대전광역시',
            provinceEn: 'Daejeon',
            labelKo: '중구',
            labelEn: 'Jung-gu',
            lat: 36.28044,
            lng: 127.41093,
          ),
        ],
      ),
      ManualLocationProvince(
        id: 'ulsan',
        labelKo: '울산광역시',
        labelEn: 'Ulsan',
        shortKo: '울산',
        shortEn: 'Ulsan',
        options: <ManualLocationOption>[
          ManualLocationOption(
            id: 'ulsan-nam',
            provinceId: 'ulsan',
            provinceKo: '울산광역시',
            provinceEn: 'Ulsan',
            labelKo: '남구',
            labelEn: 'Nam-gu',
            lat: 35.54382,
            lng: 129.32917,
          ),
          ManualLocationOption(
            id: 'ulsan-dong',
            provinceId: 'ulsan',
            provinceKo: '울산광역시',
            provinceEn: 'Ulsan',
            labelKo: '동구',
            labelEn: 'Dong-gu',
            lat: 35.50470,
            lng: 129.41860,
          ),
          ManualLocationOption(
            id: 'ulsan-buk',
            provinceId: 'ulsan',
            provinceKo: '울산광역시',
            provinceEn: 'Ulsan',
            labelKo: '북구',
            labelEn: 'Buk-gu',
            lat: 35.58243,
            lng: 129.36049,
          ),
          ManualLocationOption(
            id: 'ulsan-ulju',
            provinceId: 'ulsan',
            provinceKo: '울산광역시',
            provinceEn: 'Ulsan',
            labelKo: '울주군',
            labelEn: 'Ulju-gun',
            lat: 35.56233,
            lng: 129.12690,
          ),
          ManualLocationOption(
            id: 'ulsan-jung',
            provinceId: 'ulsan',
            provinceKo: '울산광역시',
            provinceEn: 'Ulsan',
            labelKo: '중구',
            labelEn: 'Jung-gu',
            lat: 35.56840,
            lng: 129.33226,
          ),
        ],
      ),
      ManualLocationProvince(
        id: 'sejong',
        labelKo: '세종특별자치시',
        labelEn: 'Sejong',
        shortKo: '세종',
        shortEn: 'Sejong',
        options: <ManualLocationOption>[
          ManualLocationOption(
            id: 'sejong-sejong',
            provinceId: 'sejong',
            provinceKo: '세종특별자치시',
            provinceEn: 'Sejong',
            labelKo: '세종특별자치시',
            labelEn: 'Sejong-si',
            lat: 36.48000,
            lng: 127.28900,
          ),
        ],
      ),
      ManualLocationProvince(
        id: 'gyeonggi',
        labelKo: '경기도',
        labelEn: 'Gyeonggi-do',
        shortKo: '경기',
        shortEn: 'Gyeonggi',
        options: <ManualLocationOption>[
          ManualLocationOption(
            id: 'gyeonggi-gapyeong',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '가평군',
            labelEn: 'Gapyeong-gun',
            lat: 37.83080,
            lng: 127.51522,
          ),
          ManualLocationOption(
            id: 'gyeonggi-goyang',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '고양시',
            labelEn: 'Goyang-si',
            lat: 37.65639,
            lng: 126.83500,
          ),
          ManualLocationOption(
            id: 'gyeonggi-gwacheon',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '과천시',
            labelEn: 'Gwacheon-si',
            lat: 37.43407,
            lng: 126.99989,
          ),
          ManualLocationOption(
            id: 'gyeonggi-gwangmyeong',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '광명시',
            labelEn: 'Gwangmyeong-si',
            lat: 37.44435,
            lng: 126.86499,
          ),
          ManualLocationOption(
            id: 'gyeonggi-gwangju',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '광주시',
            labelEn: 'Gwangju',
            lat: 35.16667,
            lng: 126.91667,
          ),
          ManualLocationOption(
            id: 'gyeonggi-guri',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '구리시',
            labelEn: 'Guri-si',
            lat: 37.59860,
            lng: 127.13940,
          ),
          ManualLocationOption(
            id: 'gyeonggi-gunpo',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '군포시',
            labelEn: 'Gunpo-si',
            lat: 37.34261,
            lng: 126.92149,
          ),
          ManualLocationOption(
            id: 'gyeonggi-gimpo',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '김포시',
            labelEn: 'Gimpo-si',
            lat: 37.59417,
            lng: 126.74250,
          ),
          ManualLocationOption(
            id: 'gyeonggi-namyangju',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '남양주시',
            labelEn: 'Namyangju-si',
            lat: 37.65217,
            lng: 127.24010,
          ),
          ManualLocationOption(
            id: 'gyeonggi-dongducheon',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '동두천시',
            labelEn: 'Dongducheon-si',
            lat: 37.91889,
            lng: 127.06897,
          ),
          ManualLocationOption(
            id: 'gyeonggi-bucheon',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '부천시',
            labelEn: 'Bucheon-si',
            lat: 37.49889,
            lng: 126.78306,
          ),
          ManualLocationOption(
            id: 'gyeonggi-seongnam',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '성남시',
            labelEn: 'Seongnam-si',
            lat: 37.41875,
            lng: 127.12877,
          ),
          ManualLocationOption(
            id: 'gyeonggi-suwon',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '수원시',
            labelEn: 'Suwon-si',
            lat: 37.28586,
            lng: 127.00993,
          ),
          ManualLocationOption(
            id: 'gyeonggi-siheung',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '시흥시',
            labelEn: 'Siheung-si',
            lat: 37.39067,
            lng: 126.78880,
          ),
          ManualLocationOption(
            id: 'gyeonggi-ansan',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '안산시',
            labelEn: 'Ansan-si',
            lat: 37.31693,
            lng: 126.83048,
          ),
          ManualLocationOption(
            id: 'gyeonggi-anseong',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '안성시',
            labelEn: 'Anseong-si',
            lat: 37.03789,
            lng: 127.30057,
          ),
          ManualLocationOption(
            id: 'gyeonggi-anyang',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '안양시',
            labelEn: 'Anyang-si',
            lat: 37.39250,
            lng: 126.92694,
          ),
          ManualLocationOption(
            id: 'gyeonggi-yangjusi',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '양주시',
            labelEn: 'Yangjusi',
            lat: 37.81732,
            lng: 127.04600,
          ),
          ManualLocationOption(
            id: 'gyeonggi-yangpyeong',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '양평군',
            labelEn: 'Yangpyeong-gun',
            lat: 37.48880,
            lng: 127.49222,
          ),
          ManualLocationOption(
            id: 'gyeonggi-yeoju',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '여주시',
            labelEn: 'Yeoju-si',
            lat: 37.29562,
            lng: 127.63668,
          ),
          ManualLocationOption(
            id: 'gyeonggi-yeoncheon',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '연천군',
            labelEn: 'Yeoncheon-gun',
            lat: 38.09404,
            lng: 127.07577,
          ),
          ManualLocationOption(
            id: 'gyeonggi-osan',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '오산시',
            labelEn: 'Osan-si',
            lat: 37.15222,
            lng: 127.07056,
          ),
          ManualLocationOption(
            id: 'gyeonggi-yongin',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '용인시',
            labelEn: 'Yongin-si',
            lat: 37.23825,
            lng: 127.17795,
          ),
          ManualLocationOption(
            id: 'gyeonggi-uiwang',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '의왕시',
            labelEn: 'Uiwang-si',
            lat: 37.34500,
            lng: 126.97575,
          ),
          ManualLocationOption(
            id: 'gyeonggi-uijeongbu',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '의정부시',
            labelEn: 'Uijeongbu-si',
            lat: 37.73865,
            lng: 127.04770,
          ),
          ManualLocationOption(
            id: 'gyeonggi-icheon',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '이천시',
            labelEn: 'Icheon-si',
            lat: 37.27917,
            lng: 127.44250,
          ),
          ManualLocationOption(
            id: 'gyeonggi-paju',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '파주시',
            labelEn: 'Paju-si',
            lat: 37.75952,
            lng: 126.77772,
          ),
          ManualLocationOption(
            id: 'gyeonggi-pyeongtaek',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '평택시',
            labelEn: 'Pyeongtaek-si',
            lat: 36.99472,
            lng: 127.08889,
          ),
          ManualLocationOption(
            id: 'gyeonggi-pocheonsi',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '포천시',
            labelEn: 'Pocheonsi',
            lat: 37.89370,
            lng: 127.20028,
          ),
          ManualLocationOption(
            id: 'gyeonggi-hanam',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '하남시',
            labelEn: 'Hanam-si',
            lat: 37.53895,
            lng: 127.21250,
          ),
          ManualLocationOption(
            id: 'gyeonggi-hwaseongsi',
            provinceId: 'gyeonggi',
            provinceKo: '경기도',
            provinceEn: 'Gyeonggi-do',
            labelKo: '화성시',
            labelEn: 'Hwaseongsi',
            lat: 37.20025,
            lng: 126.82909,
          ),
        ],
      ),
      ManualLocationProvince(
        id: 'gangwon',
        labelKo: '강원특별자치도',
        labelEn: 'Gangwon',
        shortKo: '강원',
        shortEn: 'Gangwon',
        options: <ManualLocationOption>[
          ManualLocationOption(
            id: 'gangwon-gangneung',
            provinceId: 'gangwon',
            provinceKo: '강원특별자치도',
            provinceEn: 'Gangwon',
            labelKo: '강릉시',
            labelEn: 'Gangneung-si',
            lat: 37.75190,
            lng: 128.87825,
          ),
          ManualLocationOption(
            id: 'gangwon-goseong',
            provinceId: 'gangwon',
            provinceKo: '강원특별자치도',
            provinceEn: 'Gangwon',
            labelKo: '고성군',
            labelEn: 'Goseong-gun',
            lat: 38.37945,
            lng: 128.46755,
          ),
          ManualLocationOption(
            id: 'gangwon-donghae',
            provinceId: 'gangwon',
            provinceKo: '강원특별자치도',
            provinceEn: 'Gangwon',
            labelKo: '동해시',
            labelEn: 'Donghae-si',
            lat: 37.52345,
            lng: 129.11357,
          ),
          ManualLocationOption(
            id: 'gangwon-samcheok',
            provinceId: 'gangwon',
            provinceKo: '강원특별자치도',
            provinceEn: 'Gangwon',
            labelKo: '삼척시',
            labelEn: 'Samcheok-si',
            lat: 37.45013,
            lng: 129.16626,
          ),
          ManualLocationOption(
            id: 'gangwon-sokcho',
            provinceId: 'gangwon',
            provinceKo: '강원특별자치도',
            provinceEn: 'Gangwon',
            labelKo: '속초시',
            labelEn: 'Sokcho-si',
            lat: 38.20725,
            lng: 128.59275,
          ),
          ManualLocationOption(
            id: 'gangwon-yanggu',
            provinceId: 'gangwon',
            provinceKo: '강원특별자치도',
            provinceEn: 'Gangwon',
            labelKo: '양구군',
            labelEn: 'Yanggu-gun',
            lat: 38.10583,
            lng: 127.98944,
          ),
          ManualLocationOption(
            id: 'gangwon-yangyang',
            provinceId: 'gangwon',
            provinceKo: '강원특별자치도',
            provinceEn: 'Gangwon',
            labelKo: '양양군',
            labelEn: 'Yangyang-gun',
            lat: 38.06215,
            lng: 128.61471,
          ),
          ManualLocationOption(
            id: 'gangwon-yeongwol',
            provinceId: 'gangwon',
            provinceKo: '강원특별자치도',
            provinceEn: 'Gangwon',
            labelKo: '영월군',
            labelEn: 'Yeongwol-gun',
            lat: 37.18330,
            lng: 128.46150,
          ),
          ManualLocationOption(
            id: 'gangwon-wonju',
            provinceId: 'gangwon',
            provinceKo: '강원특별자치도',
            provinceEn: 'Gangwon',
            labelKo: '원주시',
            labelEn: 'Wonju-si',
            lat: 37.32104,
            lng: 127.92132,
          ),
          ManualLocationOption(
            id: 'gangwon-inje',
            provinceId: 'gangwon',
            provinceKo: '강원특별자치도',
            provinceEn: 'Gangwon',
            labelKo: '인제군',
            labelEn: 'Inje-gun',
            lat: 38.04416,
            lng: 128.27876,
          ),
          ManualLocationOption(
            id: 'gangwon-jeongseon',
            provinceId: 'gangwon',
            provinceKo: '강원특별자치도',
            provinceEn: 'Gangwon',
            labelKo: '정선군',
            labelEn: 'Jeongseon-gun',
            lat: 37.38911,
            lng: 128.72995,
          ),
          ManualLocationOption(
            id: 'gangwon-gongju',
            provinceId: 'gangwon',
            provinceKo: '강원특별자치도',
            provinceEn: 'Gangwon',
            labelKo: '철원군',
            labelEn: 'Gongju-si',
            lat: 38.24391,
            lng: 127.44522,
          ),
          ManualLocationOption(
            id: 'gangwon-chuncheon',
            provinceId: 'gangwon',
            provinceKo: '강원특별자치도',
            provinceEn: 'Gangwon',
            labelKo: '춘천시',
            labelEn: 'Chuncheon-si',
            lat: 37.88048,
            lng: 127.72776,
          ),
          ManualLocationOption(
            id: 'gangwon-taebaek',
            provinceId: 'gangwon',
            provinceKo: '강원특별자치도',
            provinceEn: 'Gangwon',
            labelKo: '태백시',
            labelEn: 'Taebaek-si',
            lat: 37.16520,
            lng: 128.98570,
          ),
          ManualLocationOption(
            id: 'gangwon-pyeongchang',
            provinceId: 'gangwon',
            provinceKo: '강원특별자치도',
            provinceEn: 'Gangwon',
            labelKo: '평창군',
            labelEn: 'Pyeongchang-gun',
            lat: 37.37028,
            lng: 128.39306,
          ),
          ManualLocationOption(
            id: 'gangwon-hongcheon',
            provinceId: 'gangwon',
            provinceKo: '강원특별자치도',
            provinceEn: 'Gangwon',
            labelKo: '홍천군',
            labelEn: 'Hongcheon-gun',
            lat: 37.69180,
            lng: 127.88570,
          ),
          ManualLocationOption(
            id: 'gangwon-hwacheon',
            provinceId: 'gangwon',
            provinceKo: '강원특별자치도',
            provinceEn: 'Gangwon',
            labelKo: '화천군',
            labelEn: 'Hwacheon-gun',
            lat: 38.14212,
            lng: 127.67615,
          ),
          ManualLocationOption(
            id: 'gangwon-hoengseong',
            provinceId: 'gangwon',
            provinceKo: '강원특별자치도',
            provinceEn: 'Gangwon',
            labelKo: '횡성군',
            labelEn: 'Hoengseong-gun',
            lat: 37.48817,
            lng: 127.98570,
          ),
        ],
      ),
      ManualLocationProvince(
        id: 'chungbuk',
        labelKo: '충청북도',
        labelEn: 'Chungcheongbuk-do',
        shortKo: '충북',
        shortEn: 'Chungbuk',
        options: <ManualLocationOption>[
          ManualLocationOption(
            id: 'chungbuk-goesan',
            provinceId: 'chungbuk',
            provinceKo: '충청북도',
            provinceEn: 'Chungcheongbuk-do',
            labelKo: '괴산군',
            labelEn: 'Goesan-gun',
            lat: 36.77179,
            lng: 127.81426,
          ),
          ManualLocationOption(
            id: 'chungbuk-danyang',
            provinceId: 'chungbuk',
            provinceKo: '충청북도',
            provinceEn: 'Chungcheongbuk-do',
            labelKo: '단양군',
            labelEn: 'Danyang-gun',
            lat: 36.98615,
            lng: 128.36945,
          ),
          ManualLocationOption(
            id: 'chungbuk-boeun',
            provinceId: 'chungbuk',
            provinceKo: '충청북도',
            provinceEn: 'Chungcheongbuk-do',
            labelKo: '보은군',
            labelEn: 'Boeun-gun',
            lat: 36.49489,
            lng: 127.72865,
          ),
          ManualLocationOption(
            id: 'chungbuk-yeongdong',
            provinceId: 'chungbuk',
            provinceKo: '충청북도',
            provinceEn: 'Chungcheongbuk-do',
            labelKo: '영동군',
            labelEn: 'Yeongdong-gun',
            lat: 36.16450,
            lng: 127.79018,
          ),
          ManualLocationOption(
            id: 'chungbuk-okcheon',
            provinceId: 'chungbuk',
            provinceKo: '충청북도',
            provinceEn: 'Chungcheongbuk-do',
            labelKo: '옥천군',
            labelEn: 'Okcheon-gun',
            lat: 36.30120,
            lng: 127.56800,
          ),
          ManualLocationOption(
            id: 'chungbuk-eumseong',
            provinceId: 'chungbuk',
            provinceKo: '충청북도',
            provinceEn: 'Chungcheongbuk-do',
            labelKo: '음성군',
            labelEn: 'Eumseong-gun',
            lat: 36.92602,
            lng: 127.68070,
          ),
          ManualLocationOption(
            id: 'chungbuk-jecheon',
            provinceId: 'chungbuk',
            provinceKo: '충청북도',
            provinceEn: 'Chungcheongbuk-do',
            labelKo: '제천시',
            labelEn: 'Jecheon-si',
            lat: 37.06206,
            lng: 128.14065,
          ),
          ManualLocationOption(
            id: 'chungbuk-jeungpyeonggun',
            provinceId: 'chungbuk',
            provinceKo: '충청북도',
            provinceEn: 'Chungcheongbuk-do',
            labelKo: '증평군',
            labelEn: 'Jeungpyeonggun',
            lat: 36.78377,
            lng: 127.59858,
          ),
          ManualLocationOption(
            id: 'chungbuk-jincheon',
            provinceId: 'chungbuk',
            provinceKo: '충청북도',
            provinceEn: 'Chungcheongbuk-do',
            labelKo: '진천군',
            labelEn: 'Jincheon-gun',
            lat: 36.85667,
            lng: 127.44333,
          ),
          ManualLocationOption(
            id: 'chungbuk-cheongju',
            provinceId: 'chungbuk',
            provinceKo: '충청북도',
            provinceEn: 'Chungcheongbuk-do',
            labelKo: '청주시',
            labelEn: 'Cheongju-si',
            lat: 36.63722,
            lng: 127.48972,
          ),
          ManualLocationOption(
            id: 'chungbuk-chungju',
            provinceId: 'chungbuk',
            provinceKo: '충청북도',
            provinceEn: 'Chungcheongbuk-do',
            labelKo: '충주시',
            labelEn: 'Chungju-si',
            lat: 37.01791,
            lng: 127.87713,
          ),
        ],
      ),
      ManualLocationProvince(
        id: 'chungnam',
        labelKo: '충청남도',
        labelEn: 'Chungcheongnam-do',
        shortKo: '충남',
        shortEn: 'Chungnam',
        options: <ManualLocationOption>[
          ManualLocationOption(
            id: 'chungnam-gyeryongsi',
            provinceId: 'chungnam',
            provinceKo: '충청남도',
            provinceEn: 'Chungcheongnam-do',
            labelKo: '계룡시',
            labelEn: 'Gyeryongsi',
            lat: 36.29304,
            lng: 127.22575,
          ),
          ManualLocationOption(
            id: 'chungnam-gongju',
            provinceId: 'chungnam',
            provinceKo: '충청남도',
            provinceEn: 'Chungcheongnam-do',
            labelKo: '공주시',
            labelEn: 'Gongju-si',
            lat: 36.45556,
            lng: 127.12472,
          ),
          ManualLocationOption(
            id: 'chungnam-geumsan',
            provinceId: 'chungnam',
            provinceKo: '충청남도',
            provinceEn: 'Chungcheongnam-do',
            labelKo: '금산군',
            labelEn: 'Geumsan-gun',
            lat: 36.13381,
            lng: 127.48062,
          ),
          ManualLocationOption(
            id: 'chungnam-nonsan',
            provinceId: 'chungnam',
            provinceKo: '충청남도',
            provinceEn: 'Chungcheongnam-do',
            labelKo: '논산시',
            labelEn: 'Nonsan-si',
            lat: 36.19774,
            lng: 127.12143,
          ),
          ManualLocationOption(
            id: 'chungnam-dangjinsi',
            provinceId: 'chungnam',
            provinceKo: '충청남도',
            provinceEn: 'Chungcheongnam-do',
            labelKo: '당진시',
            labelEn: 'Dangjinsi',
            lat: 36.91667,
            lng: 126.66667,
          ),
          ManualLocationOption(
            id: 'chungnam-boryeong',
            provinceId: 'chungnam',
            provinceKo: '충청남도',
            provinceEn: 'Chungcheongnam-do',
            labelKo: '보령시',
            labelEn: 'Boryeong-si',
            lat: 36.35649,
            lng: 126.59444,
          ),
          ManualLocationOption(
            id: 'chungnam-buyeo',
            provinceId: 'chungnam',
            provinceKo: '충청남도',
            provinceEn: 'Chungcheongnam-do',
            labelKo: '부여군',
            labelEn: 'Buyeo-gun',
            lat: 36.26257,
            lng: 126.85802,
          ),
          ManualLocationOption(
            id: 'chungnam-seosan',
            provinceId: 'chungnam',
            provinceKo: '충청남도',
            provinceEn: 'Chungcheongnam-do',
            labelKo: '서산시',
            labelEn: 'Seosan-si',
            lat: 36.78518,
            lng: 126.46568,
          ),
          ManualLocationOption(
            id: 'chungnam-seocheon',
            provinceId: 'chungnam',
            provinceKo: '충청남도',
            provinceEn: 'Chungcheongnam-do',
            labelKo: '서천군',
            labelEn: 'Seocheon-gun',
            lat: 36.10820,
            lng: 126.69722,
          ),
          ManualLocationOption(
            id: 'chungnam-asan',
            provinceId: 'chungnam',
            provinceKo: '충청남도',
            provinceEn: 'Chungcheongnam-do',
            labelKo: '아산시',
            labelEn: 'Asan-si',
            lat: 36.78361,
            lng: 127.00417,
          ),
          ManualLocationOption(
            id: 'chungnam-yesan',
            provinceId: 'chungnam',
            provinceKo: '충청남도',
            provinceEn: 'Chungcheongnam-do',
            labelKo: '예산군',
            labelEn: 'Yesan-gun',
            lat: 36.68218,
            lng: 126.79592,
          ),
          ManualLocationOption(
            id: 'chungnam-cheonan',
            provinceId: 'chungnam',
            provinceKo: '충청남도',
            provinceEn: 'Chungcheongnam-do',
            labelKo: '천안시',
            labelEn: 'Cheonan-si',
            lat: 36.80488,
            lng: 127.19431,
          ),
          ManualLocationOption(
            id: 'chungnam-cheongyang',
            provinceId: 'chungnam',
            provinceKo: '충청남도',
            provinceEn: 'Chungcheongnam-do',
            labelKo: '청양군',
            labelEn: 'Cheongyang-gun',
            lat: 36.44586,
            lng: 126.84288,
          ),
          ManualLocationOption(
            id: 'chungnam-taean',
            provinceId: 'chungnam',
            provinceKo: '충청남도',
            provinceEn: 'Chungcheongnam-do',
            labelKo: '태안군',
            labelEn: 'Taean-gun',
            lat: 36.70036,
            lng: 126.28391,
          ),
          ManualLocationOption(
            id: 'chungnam-hongseong',
            provinceId: 'chungnam',
            provinceKo: '충청남도',
            provinceEn: 'Chungcheongnam-do',
            labelKo: '홍성군',
            labelEn: 'Hongseong-gun',
            lat: 36.56705,
            lng: 126.62626,
          ),
        ],
      ),
      ManualLocationProvince(
        id: 'jeonbuk',
        labelKo: '전북특별자치도',
        labelEn: 'Jeonbuk',
        shortKo: '전북',
        shortEn: 'Jeonbuk',
        options: <ManualLocationOption>[
          ManualLocationOption(
            id: 'jeonbuk-gochang',
            provinceId: 'jeonbuk',
            provinceKo: '전북특별자치도',
            provinceEn: 'Jeonbuk',
            labelKo: '고창군',
            labelEn: 'Gochang-gun',
            lat: 35.43483,
            lng: 126.70047,
          ),
          ManualLocationOption(
            id: 'jeonbuk-gunsan',
            provinceId: 'jeonbuk',
            provinceKo: '전북특별자치도',
            provinceEn: 'Jeonbuk',
            labelKo: '군산시',
            labelEn: 'Gunsan-si',
            lat: 35.93583,
            lng: 126.68338,
          ),
          ManualLocationOption(
            id: 'jeonbuk-gimje',
            provinceId: 'jeonbuk',
            provinceKo: '전북특별자치도',
            provinceEn: 'Jeonbuk',
            labelKo: '김제시',
            labelEn: 'Gimje-si',
            lat: 35.80701,
            lng: 126.90755,
          ),
          ManualLocationOption(
            id: 'jeonbuk-namwon',
            provinceId: 'jeonbuk',
            provinceKo: '전북특별자치도',
            provinceEn: 'Jeonbuk',
            labelKo: '남원시',
            labelEn: 'Namwon-si',
            lat: 35.42966,
            lng: 127.43208,
          ),
          ManualLocationOption(
            id: 'jeonbuk-muju',
            provinceId: 'jeonbuk',
            provinceKo: '전북특별자치도',
            provinceEn: 'Jeonbuk',
            labelKo: '무주군',
            labelEn: 'Muju-gun',
            lat: 35.93172,
            lng: 127.71118,
          ),
          ManualLocationOption(
            id: 'jeonbuk-buan',
            provinceId: 'jeonbuk',
            provinceKo: '전북특별자치도',
            provinceEn: 'Jeonbuk',
            labelKo: '부안군',
            labelEn: 'Buan-gun',
            lat: 35.70000,
            lng: 126.66667,
          ),
          ManualLocationOption(
            id: 'jeonbuk-sunchang',
            provinceId: 'jeonbuk',
            provinceKo: '전북특별자치도',
            provinceEn: 'Jeonbuk',
            labelKo: '순창군',
            labelEn: 'Sunchang-gun',
            lat: 35.41667,
            lng: 127.16667,
          ),
          ManualLocationOption(
            id: 'jeonbuk-wanju',
            provinceId: 'jeonbuk',
            provinceKo: '전북특별자치도',
            provinceEn: 'Jeonbuk',
            labelKo: '완주군',
            labelEn: 'Wanju-gun',
            lat: 35.84509,
            lng: 127.14752,
          ),
          ManualLocationOption(
            id: 'jeonbuk-iksan',
            provinceId: 'jeonbuk',
            provinceKo: '전북특별자치도',
            provinceEn: 'Jeonbuk',
            labelKo: '익산시',
            labelEn: 'Iksan-si',
            lat: 35.94389,
            lng: 126.95444,
          ),
          ManualLocationOption(
            id: 'jeonbuk-imsil',
            provinceId: 'jeonbuk',
            provinceKo: '전북특별자치도',
            provinceEn: 'Jeonbuk',
            labelKo: '임실군',
            labelEn: 'Imsil-gun',
            lat: 35.60660,
            lng: 127.23010,
          ),
          ManualLocationOption(
            id: 'jeonbuk-jangsu',
            provinceId: 'jeonbuk',
            provinceKo: '전북특별자치도',
            provinceEn: 'Jeonbuk',
            labelKo: '장수군',
            labelEn: 'Jangsu-gun',
            lat: 35.66667,
            lng: 127.53333,
          ),
          ManualLocationOption(
            id: 'jeonbuk-jeonju',
            provinceId: 'jeonbuk',
            provinceKo: '전북특별자치도',
            provinceEn: 'Jeonbuk',
            labelKo: '전주시',
            labelEn: 'Jeonju-si',
            lat: 35.82194,
            lng: 127.14889,
          ),
          ManualLocationOption(
            id: 'jeonbuk-jeongeup',
            provinceId: 'jeonbuk',
            provinceKo: '전북특별자치도',
            provinceEn: 'Jeonbuk',
            labelKo: '정읍시',
            labelEn: 'Jeongeup-si',
            lat: 35.60000,
            lng: 126.91667,
          ),
          ManualLocationOption(
            id: 'jeonbuk-jinan',
            provinceId: 'jeonbuk',
            provinceKo: '전북특별자치도',
            provinceEn: 'Jeonbuk',
            labelKo: '진안군',
            labelEn: 'Jinan-gun',
            lat: 35.82160,
            lng: 127.41183,
          ),
        ],
      ),
      ManualLocationProvince(
        id: 'jeonnam',
        labelKo: '전라남도',
        labelEn: 'Jeollanam-do',
        shortKo: '전남',
        shortEn: 'Jeonnam',
        options: <ManualLocationOption>[
          ManualLocationOption(
            id: 'jeonnam-gangjin',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '강진군',
            labelEn: 'Gangjin-gun',
            lat: 34.61787,
            lng: 126.76758,
          ),
          ManualLocationOption(
            id: 'jeonnam-goheung',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '고흥군',
            labelEn: 'Goheung-gun',
            lat: 34.58333,
            lng: 127.33333,
          ),
          ManualLocationOption(
            id: 'jeonnam-gokseong',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '곡성군',
            labelEn: 'Gokseong-gun',
            lat: 35.21449,
            lng: 127.26280,
          ),
          ManualLocationOption(
            id: 'jeonnam-gwangyang',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '광양시',
            labelEn: 'Gwangyang-si',
            lat: 35.02926,
            lng: 127.64882,
          ),
          ManualLocationOption(
            id: 'jeonnam-gurye',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '구례군',
            labelEn: 'Gurye-gun',
            lat: 35.20944,
            lng: 127.46444,
          ),
          ManualLocationOption(
            id: 'jeonnam-naju',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '나주시',
            labelEn: 'Naju-si',
            lat: 35.05683,
            lng: 126.67362,
          ),
          ManualLocationOption(
            id: 'jeonnam-damyang',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '담양군',
            labelEn: 'Damyang-gun',
            lat: 35.33976,
            lng: 126.99125,
          ),
          ManualLocationOption(
            id: 'jeonnam-mokpo',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '목포시',
            labelEn: 'Mokpo-si',
            lat: 34.80826,
            lng: 126.39420,
          ),
          ManualLocationOption(
            id: 'jeonnam-muan',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '무안군',
            labelEn: 'Muan-gun',
            lat: 34.95642,
            lng: 126.44041,
          ),
          ManualLocationOption(
            id: 'jeonnam-boseong',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '보성군',
            labelEn: 'Boseong-gun',
            lat: 34.81426,
            lng: 127.15765,
          ),
          ManualLocationOption(
            id: 'jeonnam-suncheon',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '순천시',
            labelEn: 'Suncheon-si',
            lat: 34.98951,
            lng: 127.39551,
          ),
          ManualLocationOption(
            id: 'jeonnam-sinan',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '신안군',
            labelEn: 'Sinan-gun',
            lat: 34.82620,
            lng: 126.10863,
          ),
          ManualLocationOption(
            id: 'jeonnam-yeosu',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '여수시',
            labelEn: 'Yeosu-si',
            lat: 34.77647,
            lng: 127.64253,
          ),
          ManualLocationOption(
            id: 'jeonnam-yeonggwang',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '영광군',
            labelEn: 'Yeonggwang-gun',
            lat: 35.28711,
            lng: 126.43616,
          ),
          ManualLocationOption(
            id: 'jeonnam-yeongam',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '영암군',
            labelEn: 'Yeongam-gun',
            lat: 34.79790,
            lng: 126.62651,
          ),
          ManualLocationOption(
            id: 'jeonnam-wando',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '완도군',
            labelEn: 'Wando-gun',
            lat: 34.31182,
            lng: 126.73845,
          ),
          ManualLocationOption(
            id: 'jeonnam-jangseong',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '장성군',
            labelEn: 'Jangseong-gun',
            lat: 35.32734,
            lng: 126.76817,
          ),
          ManualLocationOption(
            id: 'jeonnam-jangheung',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '장흥군',
            labelEn: 'Jangheung-gun',
            lat: 34.66667,
            lng: 126.91667,
          ),
          ManualLocationOption(
            id: 'jeonnam-jindo',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '진도군',
            labelEn: 'Jindo-gun',
            lat: 34.41018,
            lng: 126.16880,
          ),
          ManualLocationOption(
            id: 'jeonnam-hampyeong',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '함평군',
            labelEn: 'Hampyeong-gun',
            lat: 35.11641,
            lng: 126.53221,
          ),
          ManualLocationOption(
            id: 'jeonnam-haenam',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '해남군',
            labelEn: 'Haenam-gun',
            lat: 34.54047,
            lng: 126.51870,
          ),
          ManualLocationOption(
            id: 'jeonnam-hwasun',
            provinceId: 'jeonnam',
            provinceKo: '전라남도',
            provinceEn: 'Jeollanam-do',
            labelKo: '화순군',
            labelEn: 'Hwasun-gun',
            lat: 35.00843,
            lng: 127.02576,
          ),
        ],
      ),
      ManualLocationProvince(
        id: 'gyeongbuk',
        labelKo: '경상북도',
        labelEn: 'Gyeongsangbuk-do',
        shortKo: '경북',
        shortEn: 'Gyeongbuk',
        options: <ManualLocationOption>[
          ManualLocationOption(
            id: 'gyeongbuk-gyeongsan',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '경산시',
            labelEn: 'Gyeongsan-si',
            lat: 35.83333,
            lng: 128.80000,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-gyeongju',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '경주시',
            labelEn: 'Gyeongju-si',
            lat: 35.84278,
            lng: 129.21167,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-goryeong',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '고령군',
            labelEn: 'Goryeong-gun',
            lat: 35.74959,
            lng: 128.29707,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-gumi',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '구미시',
            labelEn: 'Gumi-si',
            lat: 36.21009,
            lng: 128.35442,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-gimcheon',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '김천시',
            labelEn: 'Gimcheon-si',
            lat: 36.14481,
            lng: 128.11157,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-mungyeong',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '문경시',
            labelEn: 'Mungyeong-si',
            lat: 36.59458,
            lng: 128.19946,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-bonghwa',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '봉화군',
            labelEn: 'Bonghwa-gun',
            lat: 36.88951,
            lng: 128.73573,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-sangju',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '상주시',
            labelEn: 'Sangju-si',
            lat: 36.41667,
            lng: 128.16667,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-seongju',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '성주군',
            labelEn: 'Seongju-gun',
            lat: 35.91888,
            lng: 128.28838,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-andong',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '안동시',
            labelEn: 'Andong-si',
            lat: 36.56636,
            lng: 128.72275,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-yeongdeok',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '영덕군',
            labelEn: 'Yeongdeok-gun',
            lat: 36.48125,
            lng: 129.31078,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-yeongyang',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '영양군',
            labelEn: 'Yeongyang-gun',
            lat: 36.69592,
            lng: 129.14196,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-yeongju',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '영주시',
            labelEn: 'Yeongju-si',
            lat: 36.87459,
            lng: 128.58631,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-yeongcheon',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '영천시',
            labelEn: 'Yeongcheon-si',
            lat: 36.00000,
            lng: 129.00000,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-yecheon',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '예천군',
            labelEn: 'Yecheon-gun',
            lat: 36.65272,
            lng: 128.43007,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-ulleung',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '울릉군',
            labelEn: 'Ulleung-gun',
            lat: 37.50442,
            lng: 130.86084,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-uljin',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '울진군',
            labelEn: 'Uljin-gun',
            lat: 36.91968,
            lng: 129.31966,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-uiseong',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '의성군',
            labelEn: 'Uiseong-gun',
            lat: 36.36122,
            lng: 128.61517,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-cheongdo',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '청도군',
            labelEn: 'Cheongdo-gun',
            lat: 35.67166,
            lng: 128.78509,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-cheongsong',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '청송군',
            labelEn: 'Cheongsong-gun',
            lat: 36.43288,
            lng: 129.05159,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-chilgok',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '칠곡군',
            labelEn: 'Chilgok-gun',
            lat: 36.01512,
            lng: 128.46138,
          ),
          ManualLocationOption(
            id: 'gyeongbuk-pohang',
            provinceId: 'gyeongbuk',
            provinceKo: '경상북도',
            provinceEn: 'Gyeongsangbuk-do',
            labelKo: '포항시',
            labelEn: 'Pohang-si',
            lat: 36.08333,
            lng: 129.36667,
          ),
        ],
      ),
      ManualLocationProvince(
        id: 'gyeongnam',
        labelKo: '경상남도',
        labelEn: 'Gyeongsangnam-do',
        shortKo: '경남',
        shortEn: 'Gyeongnam',
        options: <ManualLocationOption>[
          ManualLocationOption(
            id: 'gyeongnam-geoje',
            provinceId: 'gyeongnam',
            provinceKo: '경상남도',
            provinceEn: 'Gyeongsangnam-do',
            labelKo: '거제시',
            labelEn: 'Geoje-si',
            lat: 34.90000,
            lng: 128.66666,
          ),
          ManualLocationOption(
            id: 'gyeongnam-geochang',
            provinceId: 'gyeongnam',
            provinceKo: '경상남도',
            provinceEn: 'Gyeongsangnam-do',
            labelKo: '거창군',
            labelEn: 'Geochang-gun',
            lat: 35.68735,
            lng: 127.91142,
          ),
          ManualLocationOption(
            id: 'gyeongnam-goseong',
            provinceId: 'gyeongnam',
            provinceKo: '경상남도',
            provinceEn: 'Gyeongsangnam-do',
            labelKo: '고성군',
            labelEn: 'Goseong-gun',
            lat: 35.01478,
            lng: 128.28244,
          ),
          ManualLocationOption(
            id: 'gyeongnam-gimhae',
            provinceId: 'gyeongnam',
            provinceKo: '경상남도',
            provinceEn: 'Gyeongsangnam-do',
            labelKo: '김해시',
            labelEn: 'Gimhae-si',
            lat: 35.25000,
            lng: 128.86667,
          ),
          ManualLocationOption(
            id: 'gyeongnam-namhae',
            provinceId: 'gyeongnam',
            provinceKo: '경상남도',
            provinceEn: 'Gyeongsangnam-do',
            labelKo: '남해군',
            labelEn: 'Namhae-gun',
            lat: 34.80433,
            lng: 127.92708,
          ),
          ManualLocationOption(
            id: 'gyeongnam-miryang',
            provinceId: 'gyeongnam',
            provinceKo: '경상남도',
            provinceEn: 'Gyeongsangnam-do',
            labelKo: '밀양시',
            labelEn: 'Miryang-si',
            lat: 35.49333,
            lng: 128.74889,
          ),
          ManualLocationOption(
            id: 'gyeongnam-sacheon',
            provinceId: 'gyeongnam',
            provinceKo: '경상남도',
            provinceEn: 'Gyeongsangnam-do',
            labelKo: '사천시',
            labelEn: 'Sacheon-si',
            lat: 35.00385,
            lng: 128.06857,
          ),
          ManualLocationOption(
            id: 'gyeongnam-sancheong',
            provinceId: 'gyeongnam',
            provinceKo: '경상남도',
            provinceEn: 'Gyeongsangnam-do',
            labelKo: '산청군',
            labelEn: 'Sancheong-gun',
            lat: 35.36625,
            lng: 127.87065,
          ),
          ManualLocationOption(
            id: 'gyeongnam-yangsan',
            provinceId: 'gyeongnam',
            provinceKo: '경상남도',
            provinceEn: 'Gyeongsangnam-do',
            labelKo: '양산시',
            labelEn: 'Yangsan-si',
            lat: 35.39866,
            lng: 129.03612,
          ),
          ManualLocationOption(
            id: 'gyeongnam-uiryeong',
            provinceId: 'gyeongnam',
            provinceKo: '경상남도',
            provinceEn: 'Gyeongsangnam-do',
            labelKo: '의령군',
            labelEn: 'Uiryeong-gun',
            lat: 35.39230,
            lng: 128.26917,
          ),
          ManualLocationOption(
            id: 'gyeongnam-jinju',
            provinceId: 'gyeongnam',
            provinceKo: '경상남도',
            provinceEn: 'Gyeongsangnam-do',
            labelKo: '진주시',
            labelEn: 'Jinju-si',
            lat: 35.20445,
            lng: 128.12408,
          ),
          ManualLocationOption(
            id: 'gyeongnam-changnyeong',
            provinceId: 'gyeongnam',
            provinceKo: '경상남도',
            provinceEn: 'Gyeongsangnam-do',
            labelKo: '창녕군',
            labelEn: 'Changnyeong-gun',
            lat: 35.50822,
            lng: 128.49020,
          ),
          ManualLocationOption(
            id: 'gyeongnam-changwon',
            provinceId: 'gyeongnam',
            provinceKo: '경상남도',
            provinceEn: 'Gyeongsangnam-do',
            labelKo: '창원시',
            labelEn: 'Changwon-si',
            lat: 35.27533,
            lng: 128.65152,
          ),
          ManualLocationOption(
            id: 'gyeongnam-tongyeong',
            provinceId: 'gyeongnam',
            provinceKo: '경상남도',
            provinceEn: 'Gyeongsangnam-do',
            labelKo: '통영시',
            labelEn: 'Tongyeong-si',
            lat: 34.87360,
            lng: 128.39709,
          ),
          ManualLocationOption(
            id: 'gyeongnam-hadong',
            provinceId: 'gyeongnam',
            provinceKo: '경상남도',
            provinceEn: 'Gyeongsangnam-do',
            labelKo: '하동군',
            labelEn: 'Hadong-gun',
            lat: 35.13628,
            lng: 127.77291,
          ),
          ManualLocationOption(
            id: 'gyeongnam-haman',
            provinceId: 'gyeongnam',
            provinceKo: '경상남도',
            provinceEn: 'Gyeongsangnam-do',
            labelKo: '함안군',
            labelEn: 'Haman-gun',
            lat: 35.29117,
            lng: 128.42970,
          ),
          ManualLocationOption(
            id: 'gyeongnam-hamyang',
            provinceId: 'gyeongnam',
            provinceKo: '경상남도',
            provinceEn: 'Gyeongsangnam-do',
            labelKo: '함양군',
            labelEn: 'Hamyang-gun',
            lat: 35.55233,
            lng: 127.71196,
          ),
          ManualLocationOption(
            id: 'gyeongnam-hapcheon',
            provinceId: 'gyeongnam',
            provinceKo: '경상남도',
            provinceEn: 'Gyeongsangnam-do',
            labelKo: '합천군',
            labelEn: 'Hapcheon-gun',
            lat: 35.57410,
            lng: 128.13841,
          ),
        ],
      ),
      ManualLocationProvince(
        id: 'jeju',
        labelKo: '제주특별자치도',
        labelEn: 'Jeju',
        shortKo: '제주',
        shortEn: 'Jeju',
        options: <ManualLocationOption>[
          ManualLocationOption(
            id: 'jeju-seogwipo',
            provinceId: 'jeju',
            provinceKo: '제주특별자치도',
            provinceEn: 'Jeju',
            labelKo: '서귀포시',
            labelEn: 'Seogwipo-si',
            lat: 33.29307,
            lng: 126.49748,
          ),
          ManualLocationOption(
            id: 'jeju-jeju',
            provinceId: 'jeju',
            provinceKo: '제주특별자치도',
            provinceEn: 'Jeju',
            labelKo: '제주시',
            labelEn: 'Jeju-si',
            lat: 33.50972,
            lng: 126.52194,
          ),
        ],
      ),
    ];

List<ManualLocationOption> get manualLocationOptions => <ManualLocationOption>[
  for (final province in manualLocationProvinces) ...province.options,
];

List<ManualLocationOption> get featuredManualLocationOptions {
  final optionsById = <String, ManualLocationOption>{
    for (final option in manualLocationOptions) option.id: option,
  };
  return <ManualLocationOption>[
    for (final id in featuredManualLocationIds)
      if (optionsById[id] != null) optionsById[id]!,
  ];
}

String _localized(String language, {required String ko, required String en}) {
  return language.toLowerCase().startsWith('en') ? en : ko;
}
