from __future__ import annotations

import argparse
import json
import os
from typing import Any

from apps.api.app.core.config import get_settings
from apps.api.app.core.redaction import redact_secret_text
from apps.api.app.services.local_place_enrichment import (
    PROMPT_VERSION,
    apply_local_enrichments,
    build_local_enrichment,
    fetch_candidates,
)

CONFIRM_TEXT = "APPLY_LOCAL_PLACE_ENRICHMENT"
ALLOW_ENV = "ALLOW_LOCAL_PLACE_ENRICHMENT_APPLY"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Plan, preview, or apply local romanization for missing place English fields."
    )
    parser.add_argument("--json", action="store_true", help="Print machine-readable JSON.")
    parser.add_argument("--preview", action="store_true", help="Read DB rows and preview values.")
    parser.add_argument("--apply", action="store_true", help="Update DB rows.")
    parser.add_argument(
        "--refresh-local",
        action="store_true",
        help="Recompute rows previously generated by local_romanization.",
    )
    parser.add_argument("--confirm", default="", help=f"Required with --apply: {CONFIRM_TEXT}")
    parser.add_argument("--limit", type=int, default=500)
    parser.add_argument("--connect-timeout", type=int, default=5)
    args = parser.parse_args(argv)

    if args.limit <= 0:
        _write(args, {"ok": False, "mode": _mode(args), "error": "--limit must be positive."})
        return 2
    if args.apply and args.preview:
        _write(args, {"ok": False, "mode": "plan", "error": "Use either --apply or --preview."})
        return 2
    if not args.apply and not args.preview:
        _write(args, _plan_payload())
        return 0

    settings = get_settings()
    dsn = os.getenv("DB_DSN") or settings.db_dsn
    if not dsn:
        _write(args, {"ok": False, "mode": _mode(args), "error": "DB_DSN is not configured."})
        return 2
    if args.apply:
        guard_error = _apply_guard_error(args)
        if guard_error:
            _write(args, {"ok": False, "mode": "apply", "error": guard_error})
            return 2

    try:
        rows = fetch_candidates(
            dsn=dsn,
            limit=args.limit,
            connect_timeout=args.connect_timeout,
            refresh_local=args.refresh_local,
        )
        enrichments = [
            build_local_enrichment(row, replace_existing=args.refresh_local) for row in rows
        ]
        updated_rows = 0
        if args.apply:
            updated_rows = apply_local_enrichments(
                dsn=dsn,
                enrichments=enrichments,
                connect_timeout=args.connect_timeout,
                replace_existing=args.refresh_local,
            )
    except Exception as exc:
        _write(
            args,
            {
                "ok": False,
                "mode": _mode(args),
                "error": redact_secret_text(str(exc) or exc.__class__.__name__, (dsn,)),
            },
        )
        return 2

    _write(
        args,
        {
            "ok": True,
            "mode": _mode(args),
            "db_mutation": bool(args.apply),
            "target": "travel.places",
            "prompt_version": PROMPT_VERSION,
            "candidate_count": len(rows),
            "enrichment_count": len([item for item in enrichments if item.has_values()]),
            "updated_rows": updated_rows,
            "refresh_local": args.refresh_local,
            "preview": [item.__dict__ for item in enrichments[:5]],
        },
    )
    return 0


def _plan_payload() -> dict[str, Any]:
    return {
        "ok": True,
        "mode": "plan",
        "db_mutation": False,
        "target": "travel.places",
        "prompt_version": PROMPT_VERSION,
        "source_method": "local_romanization",
        "input_relations": ["travel.places"],
    }


def _apply_guard_error(args: argparse.Namespace) -> str:
    if args.confirm != CONFIRM_TEXT:
        return f"--apply requires --confirm {CONFIRM_TEXT}."
    if os.getenv(ALLOW_ENV) != "1":
        return f"--apply requires {ALLOW_ENV}=1 in the process environment."
    return ""


def _write(args: argparse.Namespace, payload: dict[str, Any]) -> None:
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
        return

    print("LALA-next local place enrichment")
    print(f"mode={payload.get('mode')}")
    print(f"status={'ok' if payload.get('ok') else 'degraded'}")
    print(f"target={payload.get('target', 'travel.places')}")
    print(f"prompt_version={payload.get('prompt_version', PROMPT_VERSION)}")
    if "db_mutation" in payload:
        print(f"db_mutation={str(payload.get('db_mutation')).lower()}")
    if payload.get("error"):
        print(f"error={payload['error']}")
        return
    for key in ("candidate_count", "enrichment_count", "updated_rows"):
        if key in payload:
            print(f"{key}={payload[key]}")
    if "refresh_local" in payload:
        print(f"refresh_local={str(payload['refresh_local']).lower()}")
    for item in payload.get("preview") or []:
        print(
            "preview="
            + json.dumps(
                {
                    "place_id": item.get("place_id"),
                    "name_en": item.get("name_en"),
                    "region_name_en": item.get("region_name_en"),
                },
                ensure_ascii=False,
                sort_keys=True,
            )
        )


def _mode(args: argparse.Namespace) -> str:
    return "apply" if args.apply else "preview"


if __name__ == "__main__":
    raise SystemExit(main())
