from __future__ import annotations

import argparse
import json
import os
from typing import Any

from apps.api.app.core.config import get_settings
from apps.api.app.core.redaction import redact_secret_text
from apps.api.app.services.local_place_enrichment import (
    PROMPT_VERSION,
    apply_local_enrichments,
    apply_targeted_local_enrichments,
    build_local_enrichment,
    build_targeted_name_en_enrichment,
    fetch_candidates,
    fetch_targeted_places,
    targeted_rows_error,
)

CONFIRM_TEXT = "APPLY_LOCAL_PLACE_ENRICHMENT"
ALLOW_ENV = "ALLOW_LOCAL_PLACE_ENRICHMENT_APPLY"
_DEFAULT_LIMIT = 500


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Plan, preview, or apply local romanization for missing place English fields."
    )
    parser.add_argument("--json", action="store_true", help="Print machine-readable JSON.")
    parser.add_argument("--preview", action="store_true", help="Read DB rows and preview values.")
    parser.add_argument("--apply", action="store_true", help="Update DB rows.")
    parser.add_argument(
        "--refresh-local",
        action="store_true",
        help="Recompute rows previously generated by local_romanization.",
    )
    parser.add_argument(
        "--target-place-id",
        action="append",
        default=None,
        metavar="PLACE_ID",
        help=(
            "Targeted repair: regenerate this exact place_id from its curated label. "
            "Repeatable; requires --refresh-local and --preview or --apply."
        ),
    )
    parser.add_argument("--confirm", default="", help=f"Required with --apply: {CONFIRM_TEXT}")
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--connect-timeout", type=int, default=5)
    args = parser.parse_args(argv)

    if args.limit is not None and args.limit <= 0:
        _write(args, {"ok": False, "mode": _mode(args), "error": "--limit must be positive."})
        return 2
    if args.apply and args.preview:
        _write(args, {"ok": False, "mode": "plan", "error": "Use either --apply or --preview."})
        return 2
    target_place_ids = _normalized_target_place_ids(args)
    target_error = _target_mode_error(args, target_place_ids)
    if target_error:
        _write(args, {"ok": False, "mode": _mode(args), "error": target_error})
        return 2
    if not args.apply and not args.preview:
        _write(args, _plan_payload())
        return 0

    settings = get_settings()
    dsn = os.getenv("DB_DSN") or settings.db_dsn
    if not dsn:
        _write(args, {"ok": False, "mode": _mode(args), "error": "DB_DSN is not configured."})
        return 2
    if args.apply:
        guard_error = _apply_guard_error(args)
        if guard_error:
            _write(args, {"ok": False, "mode": "apply", "error": guard_error})
            return 2

    limit = args.limit if args.limit is not None else _DEFAULT_LIMIT
    try:
        if target_place_ids:
            return _run_targeted(args, dsn=dsn, place_ids=target_place_ids)
        rows = fetch_candidates(
            dsn=dsn,
            limit=limit,
            connect_timeout=args.connect_timeout,
            refresh_local=args.refresh_local,
        )
        enrichments = [
            build_local_enrichment(row, replace_existing=args.refresh_local) for row in rows
        ]
        updated_rows = 0
        if args.apply:
            updated_rows = apply_local_enrichments(
                dsn=dsn,
                enrichments=enrichments,
                connect_timeout=args.connect_timeout,
                replace_existing=args.refresh_local,
            )
    except Exception as exc:
        _write(
            args,
            {
                "ok": False,
                "mode": _mode(args),
                "error": redact_secret_text(str(exc) or exc.__class__.__name__, (dsn,)),
            },
        )
        return 2

    _write(
        args,
        {
            "ok": True,
            "mode": _mode(args),
            "db_mutation": bool(args.apply),
            "target": "travel.places",
            "prompt_version": PROMPT_VERSION,
            "candidate_count": len(rows),
            "enrichment_count": len([item for item in enrichments if item.has_values()]),
            "updated_rows": updated_rows,
            "refresh_local": args.refresh_local,
            "preview": [item.__dict__ for item in enrichments[:5]],
        },
    )
    return 0


def _plan_payload() -> dict[str, Any]:
    return {
        "ok": True,
        "mode": "plan",
        "db_mutation": False,
        "target": "travel.places",
        "prompt_version": PROMPT_VERSION,
        "source_method": "local_romanization",
        "input_relations": ["travel.places"],
    }


def _run_targeted(args: argparse.Namespace, *, dsn: str, place_ids: list[str]) -> int:
    """Bounded targeted repair: exact-ID fetch, fail-closed validation, name-only atomic apply."""
    rows = fetch_targeted_places(
        dsn=dsn,
        place_ids=place_ids,
        connect_timeout=args.connect_timeout,
    )
    rows_error = targeted_rows_error(rows, place_ids)
    if rows_error:
        _write(args, {"ok": False, "mode": _mode(args), "error": rows_error})
        return 2
    rows_by_id = {str(row.get("place_id")): row for row in rows}
    ordered_rows = [rows_by_id[place_id] for place_id in place_ids]
    enrichments = [build_targeted_name_en_enrichment(row) for row in ordered_rows]
    missing_label = next((item.place_id for item in enrichments if not item.name_en), None)
    if missing_label:
        _write(
            args,
            {
                "ok": False,
                "mode": _mode(args),
                "error": f"target place {missing_label} has no curated name_en label; refusing.",
            },
        )
        return 2
    updated_rows = 0
    if args.apply:
        updated_rows = apply_targeted_local_enrichments(
            dsn=dsn,
            enrichments=enrichments,
            expected_name_ko={
                str(row.get("place_id")): str(row.get("name_ko")) for row in ordered_rows
            },
            connect_timeout=args.connect_timeout,
        )
    _write(
        args,
        {
            "ok": True,
            "mode": _mode(args),
            "db_mutation": bool(args.apply),
            "target": "travel.places",
            "prompt_version": PROMPT_VERSION,
            "targeted": True,
            "target_place_ids": place_ids,
            "updated_rows": updated_rows,
            "refresh_local": True,
            "name_en_only": True,
            "target_results": [
                {
                    "place_id": item.place_id,
                    "name_ko": rows_by_id[item.place_id].get("name_ko"),
                    "name_en": item.name_en,
                }
                for item in enrichments
            ],
        },
    )
    return 0


def _normalized_target_place_ids(args: argparse.Namespace) -> list[str]:
    return [place_id.strip() for place_id in (args.target_place_id or [])]


def _target_mode_error(args: argparse.Namespace, place_ids: list[str]) -> str:
    if not place_ids:
        return ""
    seen: set[str] = set()
    for place_id in place_ids:
        if not place_id:
            return "--target-place-id values must not be blank."
        if place_id in seen:
            return f"--target-place-id {place_id} was passed more than once."
        seen.add(place_id)
    if not args.refresh_local:
        return "--target-place-id requires --refresh-local."
    if not args.apply and not args.preview:
        return "--target-place-id requires --preview or --apply."
    if args.limit is not None:
        return "--limit selects broad candidates and cannot combine with --target-place-id."
    return ""


def _apply_guard_error(args: argparse.Namespace) -> str:
    if args.confirm != CONFIRM_TEXT:
        return f"--apply requires --confirm {CONFIRM_TEXT}."
    if os.getenv(ALLOW_ENV) != "1":
        return f"--apply requires {ALLOW_ENV}=1 in the process environment."
    return ""


def _write(args: argparse.Namespace, payload: dict[str, Any]) -> None:
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
        return

    print("LALA-next local place enrichment")
    print(f"mode={payload.get('mode')}")
    print(f"status={'ok' if payload.get('ok') else 'degraded'}")
    print(f"target={payload.get('target', 'travel.places')}")
    print(f"prompt_version={payload.get('prompt_version', PROMPT_VERSION)}")
    if "db_mutation" in payload:
        print(f"db_mutation={str(payload.get('db_mutation')).lower()}")
    if payload.get("error"):
        print(f"error={payload['error']}")
        return
    for key in ("candidate_count", "enrichment_count", "updated_rows"):
        if key in payload:
            print(f"{key}={payload[key]}")
    if "refresh_local" in payload:
        print(f"refresh_local={str(payload['refresh_local']).lower()}")
    if payload.get("targeted"):
        print("targeted=true")
        print(f"name_en_only={str(payload.get('name_en_only')).lower()}")
        print("target_place_ids=" + ",".join(payload.get("target_place_ids") or []))
    for item in payload.get("target_results") or []:
        print(
            "target_result="
            + json.dumps(
                {
                    "place_id": item.get("place_id"),
                    "name_ko": item.get("name_ko"),
                    "name_en": item.get("name_en"),
                },
                ensure_ascii=False,
                sort_keys=True,
            )
        )
    for item in payload.get("preview") or []:
        print(
            "preview="
            + json.dumps(
                {
                    "place_id": item.get("place_id"),
                    "name_en": item.get("name_en"),
                    "region_name_en": item.get("region_name_en"),
                },
                ensure_ascii=False,
                sort_keys=True,
            )
        )


def _mode(args: argparse.Namespace) -> str:
    return "apply" if args.apply else "preview"


if __name__ == "__main__":
    raise SystemExit(main())
