from __future__ import annotations

from datetime import UTC, datetime

from apps.api.app.schemas.docent import DocentAudioRequest, DocentScriptRequest
from apps.api.app.services import ai_service, speech_service
from apps.api.app.services.normalization import display_language


def generate_script(request: DocentScriptRequest) -> dict:
    generated_at = datetime.now(UTC).isoformat()
    if ai_service.live_ai_enabled():
        script = ai_service.generate_docent_script_text(request)
        source = "azure_openai"
    else:
        script = _fallback_script(request)
        source = "skeleton"
    return {
        "place_id": request.place_id,
        "category": request.category,
        "language": request.language,
        "mode": request.mode,
        "script": script,
        "source": source,
        "generated_at": generated_at,
        "ttl_sec": 604800,
    }


def _fallback_script(request: DocentScriptRequest) -> str:
    language_label = display_language(request.language)
    return (
        f"This is a {request.mode} {language_label} docent script for "
        f"{request.category} place {request.place_id}. "
        "It is generated by the LALA-next migration skeleton and should be "
        "replaced by the Azure OpenAI backed domain service in a later wave."
    )


def generate_audio(request: DocentAudioRequest) -> bytes:
    script = request.script.strip()
    if speech_service.live_speech_enabled():
        return speech_service.synthesize_docent_audio(request)
    header = b"ID3\x04\x00\x00\x00\x00\x00!"
    body = f"LALA-next skeleton audio: {request.language}: {script[:128]}".encode("utf-8")
    return header + body
